/* Auto-generated by genmsg_cpp for file /home/turtlebot/groovy_workspace/sandbox/dfDrone/msg/DFDMessage.msg */
#ifndef DFDRONE_MESSAGE_DFDMESSAGE_H
#define DFDRONE_MESSAGE_DFDMESSAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace dfDrone
{
template <class ContainerAllocator>
struct DFDMessage_ {
  typedef DFDMessage_<ContainerAllocator> Type;

  DFDMessage_()
  : header()
  , detected(false)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , area(0.0)
  , width(0.0)
  , height(0.0)
  {
  }

  DFDMessage_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , detected(false)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , area(0.0)
  , width(0.0)
  , height(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _detected_type;
  uint8_t detected;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _area_type;
  double area;

  typedef double _width_type;
  double width;

  typedef double _height_type;
  double height;


  typedef boost::shared_ptr< ::dfDrone::DFDMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dfDrone::DFDMessage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DFDMessage
typedef  ::dfDrone::DFDMessage_<std::allocator<void> > DFDMessage;

typedef boost::shared_ptr< ::dfDrone::DFDMessage> DFDMessagePtr;
typedef boost::shared_ptr< ::dfDrone::DFDMessage const> DFDMessageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dfDrone::DFDMessage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dfDrone::DFDMessage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dfDrone

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dfDrone::DFDMessage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dfDrone::DFDMessage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dfDrone::DFDMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "488ac62e793120616e59adb850f82dd8";
  }

  static const char* value(const  ::dfDrone::DFDMessage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x488ac62e79312061ULL;
  static const uint64_t static_value2 = 0x6e59adb850f82dd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dfDrone::DFDMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dfDrone/DFDMessage";
  }

  static const char* value(const  ::dfDrone::DFDMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dfDrone::DFDMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
bool detected\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 area\n\
float64 width\n\
float64 height\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::dfDrone::DFDMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::dfDrone::DFDMessage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::dfDrone::DFDMessage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dfDrone::DFDMessage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.detected);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.area);
    stream.next(m.width);
    stream.next(m.height);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DFDMessage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dfDrone::DFDMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dfDrone::DFDMessage_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DFDRONE_MESSAGE_DFDMESSAGE_H

