#!/usr/bin/env python2

import sys

import roslib; roslib.load_manifest('dfDrone')
import rospy
import tf.transformations
from geometry_msgs.msg import Twist

def main(argv=None):
	if argv is None:
		argv = sys.argv

	rospy.init_node('doCircle')
	p = rospy.Publisher('~cmd_vel', Twist)
	
	rospy.loginfo("about to circle")

	for i in range(10):
		twist = Twist()
		twist.angular.y = 1
		twist.angular.z = 1

		p.publish(twist)
		rospy.sleep(1)
		rospy.loginfo("moving")
	rospy.loginfo("stopping")
	twist = Twist()
	p.publish(twist)

if __name__ == "__main__":
	sys.exit(main())
