#!/usr/bin/env python2

import sys

import roslib; roslib.load_manifest('dfDrone')
import rospy
from std_msgs.msg import String

def main(argv=None):
	if argv is None:
		argv = sys.argv

	rospy.init_node('getImage')
	p = rospy.Subscriber('camera/rgb/image_color', String, convert)
	rospy.spin()
def convert(string):
	print(string)

if __name__ == "__main__":
	sys.exit(main())
