#!/usr/bin/env python2

import sys
import SimpleCV

import roslib; roslib.load_manifest('dfDrone')
import rospy
from sensor_msgs.msg import Image

def main(argv=None):
	if argv is None:
		argv = sys.argv

	rospy.init_node('getImage')
	p = rospy.Subscriber('camera/rgb/image_color', Image, convert)
	rospy.spin()
def convert(image):
	print(image.encoding)

if __name__ == "__main__":
	sys.exit(main())
