#!/usr/bin/env python2

'''
All this node does is relay camera data into detectDrone 
and then publish centroid and depth data
'''

# python default modules
import sys
import time

# ROS specifoc
import roslib; roslib.load_manifest('dfDrone')
import rospy
from sensor_msgs.msg import Image
from std_msgs.msg import Float64MultiArray

# opencv and simplecv modules
import cv
import cv2.cv as cv
from cv_bridge import CvBridge, CvBridgeError
import SimpleCV

# my modules
import detectDrone
# TODO from ..msg import DFDMessage

# I need this object to persist over ros spins
global_detector = None
global_publisher = None

# TimeSequencer is not available for python... dumb
global_depth = None
global_color = None

DEBUG_STRING = "[startDrone]"

# ROS loop
def main(argv=None):
	if argv is None:
		argv = sys.argv

	rospy.init_node('startDrone')
	rospy.loginfo("startDrone has initialized")

#	getColor = False
#	if getColor is False:
#		getColor = True
#		depth_sub = rospy.Subscriber('/camera/depth/image_rect', Image, depthCallback)
#	else:
#		getColor = False
#		color_sub = rospy.Subscriber('/camera/rgb/image_color', Image, colorCallback)
	color_sub = rospy.Subscriber('/camera/rgb/image_color', Image, colorCallback)
	rospy.spin()

def depthCallback(image):
	rospy.loginfo(DEBUG_STRING + "depth callback in startDrone")
	global_depth = image
#	if global_color is not None and global_depth is not None:
#		processImage(global_color, global_depth)

def colorCallback(image):
	rospy.loginfo(DEBUG_STRING + "color callback in startDrone")
	global_color = image

	if global_color is not None:
		processImage(global_color, global_depth)

# upon getting BOTH a new color and depth image call this callback
def processImage(colorImage, depthImage):
	rospy.loginfo(DEBUG_STRING + "processing image in startDrone")

        b = CvBridge()
        colorFrame = b.imgmsg_to_cv(colorImage, "bgr8")
        color = SimpleCV.Image(colorFrame, cv2image=True)
	depth = None

	if depthImage is not None:
		depthFrame = b.imgmsg_to_cv(depthImage, "32fc1")
		depth = SimpleCV.Image(colorFrame, cv2image=True)
	
	# create message - ugly since I do not have my custom message
	message = global_detector.process(color, depth)	
	rospy.loginfo(DEBUG_STRING + "message sent")
	global_publisher.publish(message.ros())

if __name__ == "__main__":
	# create detector with no debug option
	global_detector = detectDrone.Detector(False)
	global_publisher = rospy.Publisher("startDrone", Float64MultiArray)
	try:
		sys.exit(main())
	except rospy.ROSInterruptException:
		pass
